name: github-actions
run-name: ${{ github.actor }} do GitHub Actions
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  init :
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: intall modules
        run: npm intall 
      - name: intall jest
        run: npm i -D jest
      - name: jest test
        run: npm run test
