name: github-actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: intall modules
        run: npm install 
      - name: intall jest
        run: npm i -D jest
      # - name: mapArrToString test
      #   run: npm run test mapArrToString.test.js
      # - name: square test
      #   run: npm run test square.test.js
      # - name: validateValue test
      #   run: npm run test validateValue.test.js